### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by lordpidey**
Cleans up the main worker slightly.

### CODE REVIEW

**Comment by zamfofex** [comment]
Oh, hello! Thank you for bothering to contribute! :tada:

I have a couple notes regarding your pull request. I hope you don’t mind addressing them before I can merge:

- Could you undo the (apparently accidental) changes to the `catch` block in the `respond` function?
- Does it really make sense to handle `.jpg` (as opposed to just `.jpeg`) on the `mime` function when it’s not handled in the `route` function?
- I’m actually not sure I think I like how the `switch` statement looks more so than `if` variant, and I can’t see much benefit regarding it. If you could share why you think so, though, I’m open to being compelled!
- I think it makes sense to abide to the existing formatting styles, in particular, regarding the `mime` function, remove the trailing semicolons and putting the `switch`’s opening curly brace on its own line.
- Don’t your changes break video (MP4) thumbnails? They will be caught by the first regex and be handled like other assets, however they should redirect to the original videos for now, since there actually aren’t video thumbnails on the database (at least yet). The regex handling them properly will never be reached.
- Currently, code elsewhere makes assumptions about image thumbnails always being PNGs. Is it really beneficial to preempt JPEG thumbnails? If it is eventually decided to have them, the change on this file should be obvious and easy to make, so there is neither a robustness nor a scalability benefit, I think.
- Thrown values are always caught and handled explicitly (with the messages ignored). I’m not sure if there is a benefit to specifying a message to the thrown error.

**Comment by lordpidey** [comment]
> Could you undo the (apparently accidental) changes to the catch block in the respond function?

Whoops.  Okay.

> Does it really make sense to handle .jpg (as opposed to just .jpeg) on the mime function when it’s not handled in the route function?

Good point.  I do not know enough about the DB creation at this point to know if I should add jpg to the route or remove jpg from the mime.  Honestly, I'd rather jpg2000, but w/e

> I think it makes sense to abide to the existing formatting styles, in particular, regarding the mime function, remove the trailing semicolons and putting the switch’s opening curly brace on its own line.

The existing formatting style has my linter complain loudly.

> I’m actually not sure I think I like how the switch statement looks more so than if variant, and I can’t see much benefit regarding it. If you could share why you think so, though, I’m open to being compelled!

General wisdom is to not use long if chains over equality comparisons.  Switch also is slightly easier on the CPU, as it performs one check via hash that checks all simultaneously, rather than one comparison per possibility.

> Don’t your changes break video (MP4) thumbnails? They will be caught by the first regex and be handled like other assets, however they should redirect to the original videos for now, since there actually aren’t video thumbnails on the database (at least yet). The regex handling them properly will never be reached.

Possibly, I will investigate.  The intent was to save a redirect.  The whole mp4 thumbnail section looks a little suspicious to be honest.  It's using a 303 redirect, which seems odd.  301 or 307 seems more appropriate.  303 is for downgrading a POST to a GET.  However, we seem to be going from GET to GET.  Looking at it further, the wrangler seems to fetch the entire mp4, rather than just check for it's existence, but I can't verify this, as I can't find documentation for the `.get` method on the wrangler.

> Thrown values are always caught and handled explicitly (with the messages ignored). I’m not sure if there is a benefit to specifying a message to the thrown error.

No, there isn't, until proper logging is added.  But then again, neither is there to throwing an error, instead of an empty string.

**Comment by zamfofex** [comment]
> General wisdom is to not use long if chains over equality comparisons.

That’s not a “long chain” at all, though, it has no more than three conditional. If it starts becoming too large (five or six or so), it would suffice to refactor the function into an object literal top‐level variable.

>  Switch also is slightly easier on the CPU, as it performs one check via hash that checks all simultaneously, rather than one comparison per possibility.

I’m not going to be 100% certain, but I doubt V8 and Gecko don’t both optimize the two variants to the exact same underlying machine representation.

> It's using a 303 redirect, which seems odd. 301 or 307 seems more appropriate.

I see. That’s fair enough! I’m not really familiar with current HTTP best practices, especially regarding redirects, which I know to be historically complicated.

>  Looking at it further, the wrangler seems to fetch the entire mp4, rather than just check for it's existence

Streams are inherently asynchronous, so you don’t need to have the whole file buffered in order to pass it around and return it.

>  But then again, neither is there to throwing an error, instead of an empty string.

Yeah, that’s fair enough. I don’t mind the error message, that is fine.

- - -

I think the problem is that, now, if a request URL contains `th`, but doesn’t match the regular expression inside your `if` body’s block, the request will fail with 500 rather than 404 (e.g. `https://twdb.moe/math`). 

I don’t want to be discouraging, but I’m not really sure what those changes are trying to accomplish — it personally feels to me like the code doesn’t look as good, and I don’t really see many advantages. The potential performance gains are very likely negligible.

I feel like the changes that I think make sense are:

1) Changing 400 to 405 for the unsupported method error.
2) Changing the redirect status code to something more common for that use case.
3) Adding a message to the thrown error.

If you can simplify the pull request to only those changes, I can merge it. Although, I’d like to be able to ask that you rebase useless commits away, so they don’t clog up the commit history.

If you also want to refactor `mime` into an object literal variable preemptively, that would be fine too.

**Comment by lordpidey** [comment]
> Streams are inherently asynchronous, so you don’t need to have the whole file buffered in order to pass it around and return it.

You used an await though, which means you wait for the entire stream to finish before proceeding.

>I think the problem is that, now, if a request URL contains th, but doesn’t match the regular expression inside your if body’s block, the request will fail with 500 rather than 404

Oh dear.  You are correct.  There was an error when I was trying to apply your code standards.  Having two nested if statements be on the same indentation level really messes with my instincts.

>I don’t want to be discouraging, but I’m not really sure what those changes are trying to accomplish

Before you ran up to three regexes on the same string.  Now it will run a maximum of one of them.  Regexes are one of the more common things leveraged in DDOS attacks.

**Comment by zamfofex** [comment]
I have merged the pull request, but feel free to continue the conversation if you want!

> You used an await though, which means you wait for the entire stream to finish before proceeding.

Ah, I see where your confusion comes from! It’s interesting to notice that streams are *not* the same thing as promises. In order to materialize the whole stream, I would have to do something more explicit, likely using `stream.getReader()` and `await reader.read()`. You can think about it like `fetch`: When I write `response = await fetch("https://...")`, even though I used `await`, it doesn’t actually download the whole thing until I write e.g. `await response.arrayBuffer()` or `await response.text()`.

> Before you ran up to three regexes on the same string. Now it will run a maximum of one of them. Regexes are one of the more common things leveraged in DDOS attacks.

Well, those regexes are very simple and predictable. You could say this style encourages potentially dangerous regexes, but since the worker is running on Cloudflare’s servers, it’s unlikely to be dangerous, especially because for each request, the worker can run for no longer than 50ms.

**Pull request merged**
